PKGDIR			?= ../../..
L4DIR			?= $(PKGDIR)/../..

REQUIRES_LIBS   = libstdc++ libsupc++

TARGET			= libycsbc_serializer.a
PRIVATE_INCDIR  = $(PKGDIR)/server/include

SRC_CC			= serializer.cc

include $(L4DIR)/mk/lib.mk
